# Same cluster as Part 3, but with ports 80 and 443 published on the host
# so the GitLab Ingress is reachable at http://gitlab.gitlab.local
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: iot
servers: 1
agents: 1
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: --disable=metrics-server
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
