Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  
  config.vm.define "yourloginS" do |server|
    server.vm.hostname = "yourloginS"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    server.vm.provider "virtualbox" do |vb|
      vb.name = "yourloginS"
      vb.memory = "1024"
      vb.cpus = 1
    end

    server.vm.provision "shell", inline: <<-SHELL
      echo "🚀 Installing K3s Server..."
      # تثبيت K3s مع تعطيل الخصائص غير الضرورية لتوفير RAM
      curl -sfL https://get.k3s.io | sh -s - server \
        --node-ip=192.168.56.110 \
        --flannel-iface=enp0s8 \
        --write-kubeconfig-mode "644" \
        --disable metrics-server \
        --disable local-storage
      
      export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
      
      echo "⏳ Waiting for K3s Node to be ready..."
      sleep 15
      
      echo "⏳ Waiting for Traefik (Ingress) to deploy (This prevents crashing)..."
      kubectl wait --for=condition=Available deployment/traefik -n kube-system --timeout=120s || sleep 20
      
      echo "📦 Deploying Applications automatically..."
      kubectl apply -f /vagrant/confs/app.yaml
      
      echo "✅ All done! Environment is ready."
    SHELL
  end
end
