Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  
  # ==========================================
  # Server (Control Plane)
  # ==========================================
  config.vm.define "yourloginS" do |server|
    server.vm.hostname = "yourloginS"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    server.vm.provider "virtualbox" do |vb|
      vb.name = "yourloginS"
      vb.memory = "1024"
      vb.cpus = 1
    end

    server.vm.provision "shell", inline: <<-SHELL
      echo "Installing K3s Server..."
      # تعطيل metrics-server و traefik لتخفيف الضغط على CPU و RAM
      curl -sfL https://get.k3s.io | sh -s - server \
	  --node-ip=192.168.56.110 \
	  --flannel-iface=enp0s8 \
	  --write-kubeconfig-mode "644" \
	  --disable traefik \
	  --disable metrics-server
      
      # إعداد kubectl للمستخدم vagrant
      mkdir -p /home/vagrant/.kube
      cp /etc/rancher/k3s/k3s.yaml /home/vagrant/.kube/config
      chown -R vagrant:vagrant /home/vagrant/.kube
      chmod 600 /home/vagrant/.kube/config

      # حفظ التوكن للـ Worker
      cat /var/lib/rancher/k3s/server/node-token > /vagrant/node-token
    SHELL
  end

  # ==========================================
  # Worker (Agent)
  # ==========================================
  config.vm.define "yourloginSW" do |worker|
    worker.vm.hostname = "yourloginSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "yourloginSW"
      vb.memory = "1024"
      vb.cpus = 1
    end

    worker.vm.provision "shell", inline: <<-SHELL
      echo "Installing K3s Agent..."
      
      # الانتظار حتى يتم إنشاء التوكن من طرف السيرفر
      while [ ! -f /vagrant/node-token ]; do
        sleep 2
      done
      
      TOKEN=$(cat /vagrant/node-token)
      
      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$TOKEN sh -s - agent \
        --node-ip=192.168.56.111 \
        --flannel-iface=enp0s8
    SHELL
  end
end
